# Site settings
title: This is Jamin Xie
author:
  name: Jamin Xie
  email: jmxie2012@gmail.com
description: "About Me"

# Build settings
remote_theme: jekyll/minima

header_pages:
  - about.md
  - home.md
  #- extra.md

github_username: evanwill
