# Site settings
title: This is Jamin Xie
author:
  name: Jamin Xie
  email: jmxie2012@gmail.com
description: "About Me"

# Build settings
remote_theme: jekyll/minima

# minima:
#   skin: dark

header_pages:
  - about.md
  - home.md
  - extra.md

github_username: evanwill

social-network-links:
  email: "someone@example.com"
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  facebook: deanattali
  github: daattali
  twitter: daattali
  patreon: DeanAttali
  youtube: c/daattali
